// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
<<<<<<< HEAD
    apiKey: 'AIzaSyDiMgUp4YWGGZ7IPyMcJ_COZO2Z1mvm3To',
    appId: '1:854785838969:web:0ec9a64763344bdf0929a8',
    messagingSenderId: '854785838969',
    projectId: 'e-commercefirebase-b09fe',
    authDomain: 'e-commercefirebase-b09fe.firebaseapp.com',
    storageBucket: 'e-commercefirebase-b09fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUsEkoF3ycJTfQ1jgo8GvnFeo9x4Ppfio',
    appId: '1:854785838969:android:331edf367a36c23d0929a8',
    messagingSenderId: '854785838969',
    projectId: 'e-commercefirebase-b09fe',
    storageBucket: 'e-commercefirebase-b09fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzqgSgkXnrcWg9qMHqGeKxZF_yldeccsk',
    appId: '1:854785838969:ios:23d34c681ca63bd60929a8',
    messagingSenderId: '854785838969',
    projectId: 'e-commercefirebase-b09fe',
    storageBucket: 'e-commercefirebase-b09fe.appspot.com',
=======
    apiKey: 'AIzaSyA9H1awUokzQJO2upDvwrkOWetI0AevAUQ',
    appId: '1:1038218409609:web:b4804a8dc67af5f2b6f858',
    messagingSenderId: '1038218409609',
    projectId: 'e-commercefire-e7220',
    authDomain: 'e-commercefire-e7220.firebaseapp.com',
    storageBucket: 'e-commercefire-e7220.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS-e3eGU09IgWtYIFfBDTy81pEOY5jZZg',
    appId: '1:1038218409609:android:67c64364255ed227b6f858',
    messagingSenderId: '1038218409609',
    projectId: 'e-commercefire-e7220',
    storageBucket: 'e-commercefire-e7220.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArUq32gffecx1BowtSb96nQEWcJP4Wpgs',
    appId: '1:1038218409609:ios:04740619963ae608b6f858',
    messagingSenderId: '1038218409609',
    projectId: 'e-commercefire-e7220',
    storageBucket: 'e-commercefire-e7220.appspot.com',
>>>>>>> e763aa1457bfd7182f6d678d543f79ef13ce4d16
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
<<<<<<< HEAD
    apiKey: 'AIzaSyBzqgSgkXnrcWg9qMHqGeKxZF_yldeccsk',
    appId: '1:854785838969:ios:23d34c681ca63bd60929a8',
    messagingSenderId: '854785838969',
    projectId: 'e-commercefirebase-b09fe',
    storageBucket: 'e-commercefirebase-b09fe.appspot.com',
=======
    apiKey: 'AIzaSyArUq32gffecx1BowtSb96nQEWcJP4Wpgs',
    appId: '1:1038218409609:ios:04740619963ae608b6f858',
    messagingSenderId: '1038218409609',
    projectId: 'e-commercefire-e7220',
    storageBucket: 'e-commercefire-e7220.appspot.com',
>>>>>>> e763aa1457bfd7182f6d678d543f79ef13ce4d16
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
<<<<<<< HEAD
    apiKey: 'AIzaSyDiMgUp4YWGGZ7IPyMcJ_COZO2Z1mvm3To',
    appId: '1:854785838969:web:33fa684e5eec28c50929a8',
    messagingSenderId: '854785838969',
    projectId: 'e-commercefirebase-b09fe',
    authDomain: 'e-commercefirebase-b09fe.firebaseapp.com',
    storageBucket: 'e-commercefirebase-b09fe.appspot.com',
  );

}
=======
    apiKey: 'AIzaSyA9H1awUokzQJO2upDvwrkOWetI0AevAUQ',
    appId: '1:1038218409609:web:d10f2997624d3d9eb6f858',
    messagingSenderId: '1038218409609',
    projectId: 'e-commercefire-e7220',
    authDomain: 'e-commercefire-e7220.firebaseapp.com',
    storageBucket: 'e-commercefire-e7220.appspot.com',
  );
}
>>>>>>> e763aa1457bfd7182f6d678d543f79ef13ce4d16
